// Generated by CoffeeScript 1.8.0
(function() {
  var UserProfiles;

  UserProfiles = (function() {
    function UserProfiles() {}

    UserProfiles.prototype.getPropertiesForAccountName = function(accountName, cb) {
      var config, processRequest;
      processRequest = function(err, res, body) {
        if (!body || !JSON.parse(body).d) {
          return cb("no account of : " + accountName);
        } else {
          return cb(err, JSON.parse(body).d);
        }
      };
      config = {
        headers: {
          Accept: "application/json;odata=verbose"
        },
        strictSSL: this.settings.strictSSL,
        url: "" + this.url + "/_api/SP.UserProfiles.PeopleManager/GetPropertiesFor(accountName=@v)?@v='" + accountName + "'"
      };
      this.request.get(config, processRequest).auth(this.user, this.pass, true);
      return this;
    };

    return UserProfiles;

  })();

  module.exports = UserProfiles;

}).call(this);
